
API_KEY = ""
API_SECRET = ""

# define modes of research and their search query
MoR = {
    'bitcoin': 'bitcoin AND #BTC lang:en',
    'ethereum': 'ethereum AND #ETH lang:en',
    'tether': 'tether AND #USDT lang:en',
    'cardano': 'cardano lang:en AND #ADA lang:en',
    'polkadot': 'polkadot AND #DOT lang:en',
    'ripple': 'riple AND #XRP lang:en',
    'uniswap': 'uniswap AND #UNI lang:en',
    'litecoin': 'litecoin AND #LTC lang:en',
    'chainlink': 'chainlink AND #LINK lang:en',
    'usdcoin': 'usdcoin AND #USDC lang:en',
    'bitcoincash': 'bitcoincash AND #BCH lang:en',
    'lumen': 'lumen AND #XLM lang:en',
    'dogecoin': 'dogecoin AND #DOGE lang:en',
    'filecoin': 'filecoin AND #FIL lang:en',
    'tron': 'tron AND #TRX lang:en',
    'aave': 'aave AND #aave lang:en',
    'cosmos': 'cosmos AND #ATOM lang:en',
    'monero': 'monero AND #XMR lang:en',
    'eos': 'eos AND #EOS lang:en',
    'kusama': 'kusama AND #KSM lang:en',
    'tezos': 'tezos AND #XTZ lang:en',
    'algorand': 'algorand AND #ALGO lang:en',
    'dai': 'dai AND #DAI lang:en',
    'synthetix': 'synthetix AND #SNX lang:en',
    'dash': 'dash AND #DASH lang:en',
    'thegraph': 'the graph AND #GRT lang:en',
    'compound': 'compound AND #COMP lang:en',
    'bat': 'basic attention token AND #BAT lang:en',
    'zcash': 'zcash AND #ZEC lang:en',
    'decentraland': 'decentraland AND #MANA lang:en',
    'etherclassic': 'ethereum classic AND #ETC lang:en',
    'yearn': 'yearn finance AND #YFI lang:en',
    'icon': 'icon AND #ICX lang:en',
    'siacoin': 'siacoin AND #SC lang:en',
    'waves': 'waves AND #WAVES lang:en',
    'flow': 'flow AND #FLOW lang:en',
    'omg': 'omg network AND #OMG lang:en',
    'ocean': 'ocean token AND #OCEAN lang:en',
    'qtum': 'qtum AND #QTUM lang:en',
    'curve': 'curve dao token AND #CRV lang:en',
    'nano': 'nano AND #NANO lang:en',
    'kyber': 'kyber network AND #KNC lang:en',
    'energy': 'energy web token AND #EWT lang:en',
    'lisk': 'lisk AND #LSK lang:en',
    'balancer': 'balancer AND #BAL lang:en',
    'augur': 'augur AND #REP lang:en',
    'augur2': 'augur v2 AND #REPV2 lang:en',
    'keep': 'keep network AND #KEEP lang:en',
    'kava': 'kava AND #KAVA lang:en',
    'aragon': 'aragon AND #ANT lang:en',
    'orchid': 'orchid AND #OXT lang:en',
    'storj': 'storj AND #STORJ lang:en',
    'gnosis': 'gnosis AND #GNO lang:en',
    'enzyme': 'enzyme finance AND #MLN lang:en',
    'pax': 'pax gold AND #PAXG lang:en',
    'tbtc': 'tbtc AND #TBTC lang:en',    
}